# Generated by Django 4.2.6 on 2023-10-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_cmssliders_cms_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmssliders',
            name='cms_text',
            field=models.CharField(max_length=300, verbose_name='Текст'),
        ),
    ]
