# Generated by Django 4.2.6 on 2023-10-12 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_alter_order_options_alter_order_order_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
    ]
